name: Test Against OS Packages

on:
  push:
    paths:
      - 'piku.py'
      - 'piku'
      - 'requirements.txt'
      - '.github/workflows/os-packages.yml'
      - '.github/workflows/bookworm/**'
      - '.github/workflows/trixie/**'
      - '.github/workflows/noble/**'
      - '.github/workflows/plucky/**'
  pull_request:
    paths:
      - 'piku.py'
      - 'piku'
      - 'requirements.txt'
      - '.github/workflows/os-packages.yml'
      - '.github/workflows/bookworm/**'
      - '.github/workflows/trixie/**'
      - '.github/workflows/noble/**'
      - '.github/workflows/plucky/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        distro: [bookworm, trixie, noble, plucky]

    steps:
    - uses: actions/checkout@v4
    - name: Test on ${{ matrix.distro }}
      run: |
        docker build .github/workflows/${{ matrix.distro }} -t local/${{ matrix.distro }}
        docker run -v "$PWD":/run local/${{ matrix.distro }}
